name: adaptive_app_demos
description: Demo code for adaptive app development techniques.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bitsdojo_window: ^0.1.0+1
  flextras: ^0.0.2
  provider: ^5.0.0
  universal_platform: ^1.0.0-nullsafety
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+8
  google_fonts: ^2.3.1
  intl: ^0.17.0
  animations: ^2.0.2
  firebase_storage: ^10.2.7
  change_app_package_name: ^1.0.0
  adaptive_breakpoints: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  generate: true