// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXNF1HG6tS3YmLYMvyxhNFG9pd9sVl4g',
    appId: '1:87223649270:web:7d6758b108cd2d481cfdd7',
    messagingSenderId: '87223649270',
    projectId: 'easyquote-c68a0',
    authDomain: 'easyquote-c68a0.firebaseapp.com',
    storageBucket: 'easyquote-c68a0.appspot.com',
    measurementId: 'G-K3FCFBWKSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaX8ZZrxTFvFG8UlRMK4oWcn6Ml2H3__o',
    appId: '1:87223649270:android:ba3793f8cd0b86321cfdd7',
    messagingSenderId: '87223649270',
    projectId: 'easyquote-c68a0',
    storageBucket: 'easyquote-c68a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFBLWyaOQ4692-S8AASyEzLCFiHywNikQ',
    appId: '1:87223649270:ios:46ecae6cc77921eb1cfdd7',
    messagingSenderId: '87223649270',
    projectId: 'easyquote-c68a0',
    storageBucket: 'easyquote-c68a0.appspot.com',
    iosClientId: '87223649270-fd6h2ccinqpsumj5sn6e5ou49csjt7ou.apps.googleusercontent.com',
    iosBundleId: 'com.gadgetoflife.easyquote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFBLWyaOQ4692-S8AASyEzLCFiHywNikQ',
    appId: '1:87223649270:ios:46ecae6cc77921eb1cfdd7',
    messagingSenderId: '87223649270',
    projectId: 'easyquote-c68a0',
    storageBucket: 'easyquote-c68a0.appspot.com',
    iosClientId: '87223649270-fd6h2ccinqpsumj5sn6e5ou49csjt7ou.apps.googleusercontent.com',
    iosBundleId: 'com.gadgetoflife.easyquote',
  );
}
